#Day 1

Q1. Import the numpy package under the name np

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.21.6


Q3. Create a null vector of size 10

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Q4. How to find the memory size of any array

In [ ]:
x=np.arange(10)

In [ ]:
np.size(x)

10

Q4. How to get the documentation of the numpy add function from the command line?

In [ ]:
print(np.info(np.arange(10)))

class:  ndarray
shape:  (10,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x2376ad0
byteorder:  little
byteswap:  False
type: int64
None


Q5. reate a null vector of size 10 but the fifth value which is 1

In [ ]:
x=np.zeros(10) 

In [ ]:
x[4]=1

In [ ]:
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Q7.Create a vector with values ranging from 10 to 49

In [ ]:
X=np.arange(10,49)
X

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Q8. Reverse a vector (first element becomes last)

In [ ]:
z=[]
i=len(X)
while(i>=1):
  z.append(X[i-1])
  i=i-1
print(z)

[48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10]


Q9. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
print(np.arange(0, 9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Q10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [ ]:
x=np.array([1,2,0,0,4,0])

In [ ]:
inices=np.where(x==0)

In [ ]:
print(inices)

(array([2, 3, 5]),)


Q11. Create a 3x3 identity matrix

In [ ]:
matrix=np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q12. Create a 3x3x3 array with random values

In [ ]:
x = np.random.random((3,3,3))
print(x)

[[[0.31396528 0.90292568 0.84445487]
  [0.25034476 0.49664935 0.07803354]
  [0.42157625 0.81075496 0.54876055]]

 [[0.93417847 0.0228246  0.38042547]
  [0.58675086 0.22528223 0.48000223]
  [0.85770262 0.8795055  0.66323682]]

 [[0.01297059 0.56916994 0.37309324]
  [0.77641139 0.99349831 0.61669589]
  [0.92758816 0.94475106 0.6038866 ]]]


Q13. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
x = np.random.random((10,10))
print(x)

[[0.16564023 0.66890738 0.16959434 0.21359304 0.57842033 0.7857822
  0.66294464 0.03608938 0.21730097 0.33599553]
 [0.49705079 0.06056211 0.12800118 0.05979346 0.77631197 0.61818592
  0.26410779 0.57244812 0.78995188 0.48739951]
 [0.21097537 0.4900417  0.83014871 0.71659938 0.04118286 0.59518824
  0.87363922 0.01030276 0.34715621 0.76517649]
 [0.27701071 0.28929335 0.72805811 0.39308954 0.62959372 0.85347574
  0.37127706 0.77211208 0.50848257 0.03072755]
 [0.24506843 0.81302131 0.27596176 0.32945867 0.2898116  0.97804965
  0.83832949 0.04861099 0.80061834 0.09874281]
 [0.35175387 0.07805082 0.18043163 0.49158345 0.50325356 0.06328831
  0.71254514 0.19174047 0.46475427 0.7420445 ]
 [0.39780043 0.06685005 0.38406374 0.19794054 0.12369544 0.80202474
  0.09444556 0.30562242 0.09968417 0.02018567]
 [0.35285156 0.44416802 0.14005347 0.72779989 0.10246567 0.39044978
  0.91841062 0.06179923 0.25116004 0.39417665]
 [0.39031298 0.35086252 0.11785859 0.2883688  0.24854393 0.65188092
  0.09635643 

Q14. Create a random vector of size 30 and find the mean value

In [ ]:
x = np.random.random(30)
print(x)

[0.98822133 0.90091289 0.08017513 0.23660569 0.67670281 0.73805814
 0.79564451 0.0138332  0.51103084 0.98214606 0.88445913 0.62126399
 0.75496438 0.47280774 0.84156615 0.75705198 0.10987106 0.63562891
 0.33334368 0.30740683 0.35318612 0.10337568 0.00406728 0.70052496
 0.95847165 0.93526189 0.6847826  0.91602875 0.94573265 0.33534691]


Q15. Create a 2d array with 1 on the border and 0 inside

In [ ]:
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Q16. How to add a border (filled with 0's) around an existing array?

Q17. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Q18. Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Q19. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


Q20. Create a checkerboard 8x8 matrix using the tile function

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#DAY 2

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive


In [ ]:
student_list={'name':['a','b','c','d','e','f'],'age':[15,20,22,25,26],'city':['city1','city2','city3','city4','city5'],'percentage':[10,20,30.5,45.2,63.2]}

In [ ]:
a=pd.Series(student_list)

In [ ]:
a['name']

['a', 'b', 'c', 'd', 'e', 'f']

In [ ]:
print('percentage are',a['percentage'],'age are', a['age'])

percentage are [10, 20, 30.5, 45.2, 63.2] age are [15, 20, 22, 25, 26]


In [ ]:
for i in a['percentage']:
  if i>=20:
    print(i)

20
30.5
45.2
63.2


In [ ]:
for i in a['percentage']:
  if i<=30:
    print(i)

10
20


In [ ]:
for i in a['percentage']:
  if i==30:
    print(i)

READING FILE EXERCEISE

In [ ]:
file1 ='/gdrive/MyDrive/ML ASSI/ex1.csv'
df1 = pd.read_csv(file1)

In [ ]:
df1

a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
file2 ='/gdrive/MyDrive/ML ASSI/ex2.csv'
df2 = pd.read_csv(file2)

In [ ]:
df2

1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [ ]:
file3 ='/gdrive/MyDrive/ML ASSI/ex3.txt'
df3 = pd.read_csv(file3)

In [ ]:
df3

A         B         C
0  aaa -0.264438 -1.026059 -0.619500
1  bbb  0.927272  0.302904 -0.032399
2  ccc -0.264273 -0.386314 -0.217601
3  ddd -0.871858 -0.348382  1.100491

In [ ]:
file4 ='/gdrive/MyDrive/ML ASSI/ex4.csv'
df4 = pd.read_csv(file4)

In [ ]:
df4

# hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [ ]:
file5 ='/gdrive/MyDrive/ML ASSI/ex5.csv'
df5 = pd.read_csv(file5)

In [ ]:
df5

something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
file6 ='/gdrive/MyDrive/ML ASSI/ex6.csv'
df6 = pd.read_csv(file6)

In [ ]:
df6

one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [ ]:
file7 ='/gdrive/MyDrive/ML ASSI/ex7.csv'
df7 = pd.read_csv(file7)

In [ ]:
df7

a  b  c
0  1  2  3
1  1  2  3

In [ ]:
file8 ='/gdrive/MyDrive/ML ASSI/data.txt'
df8 = pd.read_csv(file8)

In [ ]:
df8

1  13  21  11  196  75  4   3  34  6  7  8  0  1.1  2  3.1  4.1   5
0  3  42  12  33  766  75  4  55   6  4  3  4  5    6  7    0   11  12
1  1  22  33  11  999  11  2   1  78  0  1  2  9    8  7    1   76  88

#changing column name

In [ ]:
df1.rename(columns = {'a':'a1','b':'b1','c':'c1','d':'d1'}, inplace = True)

#changing index of dataframe

In [ ]:
df1

a1  b1  c1  d1 message
0   1   2   3   4   hello
1   5   6   7   8   world
2   9  10  11  12     foo

In [ ]:
df1.set_index("a1")

b1  c1  d1 message
a1                    
1    2   3   4   hello
5    6   7   8   world
9   10  11  12     foo

#Try to read .json file